---
- name: make haproxy config dir
  file: 
      path: /etc/haproxy
      state: directory

- name: start haproxy as static pod
  template: 'src={{ item.src }} dest={{ item.dest }} mode=0644'
  with_items:
     - {src: '/etc/ansible/roles/haproxy/templates/haproxy.cfg.j2' , dest: '/etc/haproxy/haproxy.cfg'}
     - {src: '/etc/ansible/roles/haproxy/templates/haproxy.yaml.j2' , dest: '/etc/kubernetes/manifests/haproxy.yaml'}
