---
- hosts: k8s-all
  roles:
  - { role: base }

- hosts: k8s-master
  roles:
  - { role: etcd, when: order is defined }
  - { role: kube-master, when: order is defined }

- hosts: k8s-master
  roles:
  - { role: haproxy, when: lb is defined}

- hosts: k8s-master
  roles:
  - { role: keepalived, when: lb is defined}

- hosts: k8s-all
  roles:
  - { role: kube-proxy }

- hosts: k8s-all
  roles:
  - { role: kube-node }
