---
- hosts: k8s-master
  roles:
  - { role: keepalived, when: lb is defined}
#- hosts: slb
#  roles:
#  - { role: haproxy }
#  - { role: keepalived }
#
#- hosts: k8s-node
#  roles:
#    - [role: node]
