---
#- name: pull calico image
#  shell: 'docker pull {{ item }}'
#  with_items:
#    - quay.io/calico/node:v3.2.0
#    - quay.io/calico/cni:v3.2.0
#    - quay.io/calico/kube-controllers:v3.2.0

- name: copy kubernetes.tar.gz
  copy: 'src=/data/kube{{ k8s_version }}.tar.gz dest=/root/ mode=0644'

- name: init every node 
  shell: 'cd /root && {{ item }}'
  with_items:
  - tar zxvf kube{{ k8s_version }}.tar.gz
  - cd kube/shell && sh init.sh
